// "Create" stub created by 'zapier convert'. This is just a stub - you will need to edit!
const { replaceVars } = require('../utils');

const makeRequest = (z, bundle) => {
  const scripting = require('../scripting');
  const legacyScriptingRunner = require('zapier-platform-legacy-scripting-runner')(scripting);

  bundle._legacyUrl = 'https://gw.cmtelecom.com/v1.0/message';
  bundle._legacyUrl = replaceVars(bundle._legacyUrl, bundle);

  // Do a _pre_write() from scripting.
  const preWriteEvent = {
    name: 'create.pre',
    key: 'hybrid_messages'
  };
  return legacyScriptingRunner
    .runEvent(preWriteEvent, z, bundle)
    .then(preWriteResult => z.request(preWriteResult))
    .then(response => {
      response.throwForStatus();

      // Do a _post_write() from scripting.
      const postWriteEvent = {
        name: 'create.post',
        key: 'hybrid_messages',
        response
      };
      return legacyScriptingRunner.runEvent(postWriteEvent, z, bundle);
    });
};

module.exports = {
  key: 'hybrid_messages',
  noun: 'Message',

  display: {
    label: 'Send Hybrid Message',
    description:
      'Send a hybrid message, which means a Push notification or an SMS when the user cannot be reached via push. The zap uses the channels that you allow.',
    hidden: false,
    important: true
  },

  operation: {
    inputFields: [
      {
        key: 'Body',
        label: 'Body',
        helpText: 'Please provide the content of message.',
        type: 'string',
        required: true
      },
      {
        key: 'From',
        label: 'From',
        helpText: "Please provide sender's name.",
        type: 'string',
        required: true
      },
      {
        key: 'Reference',
        label: 'Reference',
        helpText: 'Please set the reference.',
        type: 'string',
        required: false,
        default: 'none'
      },
      {
        key: 'To',
        label: 'To',
        helpText: 'Please provide the recipient number(with country code) to whom you want to send the message.',
        type: 'string',
        required: true
      },
      {
        key: 'allowedChannels',
        label: 'Allowed Channels',
        helpText: 'Please select the appropriate channel by which you want to send the message.',
        type: 'string',
        required: false,
        choices: { push_sms: 'Push or SMS', push: 'Push only', sms: 'SMS only' }
      },
      {
        key: 'appkey',
        label: 'App Key',
        helpText:
          'Please provide the app key that was generated by the app manager after the creation of app inside app manager.',
        type: 'string',
        required: true
      }
    ],
    outputFields: [
      {
        key: 'Status',
        type: 'string'
      }
    ],
    perform: makeRequest,
    sample: { Status: 'Success' }
  }
};
